# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fa4229d5fea194532c34a0a7cd4c968cbc3a5068ed7b4e3133c5501414eefa0226eaca6b5cb03a3b398c3c60c61dd87f8920560f7ee7b474ce305a5fddcb3a4

test:
  secret_key_base: e28de21a2450b36f8523b7a676ca9a3a4c0b52b0a72576dbfb0fedc53fdf86cfb16719f34b9a79dbb85e2599df4eb50f0ac3bb9a14095e0b02010eafd60b5685

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
